title: "r00t26"
description: "Security researcher."
url: "https://erik-dzibela.github.io"
baseurl: ""

author:
  name: "r00t26"
  github: "r00t26"

# Collections
collections:
  writeups:
    output: true
    permalink: /writeups/:name/
  tools:
    output: true
    permalink: /tools/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeup"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"

# Build
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
